### PR TITLE
Remove channels and replace ruleresults true/false with weights

### PR DESCRIPTION
**Pull request by Lenbkr**
Issues: #169 & #170

### CODE REVIEW

**Review by Sandy-at-Tazama — COMMENTED** [review]
## Readme

1.  https://github.com/ActioFRM/uml-diagrams/blob/main/TP.plantuml - link to ActioFRM

2. https://github.com/ActioFRM/typology-processor - link to ActioFRM

3. Sample response in TP  `broken in confluence` - I am not sure what this means - all documentation should now be in GitHub

4. Acceptance Criteria `8. Update documentation as follows:` - I was expecting headings as specified. @Justus-at-Tazama

**Comment by Justus-at-Tazama** [comment]
image

**Review by Justus-at-Tazama — APPROVED** [review]
Integration testing successful for rule-901.

**Review by Sandy-at-Tazama — DISMISSED** [review]

**Review by rtkay123 — APPROVED** [review]

**Review by rtkay123 — APPROVED** [review]

**Review by Justus-at-Tazama — APPROVED** [review]
image

**Pull request merged**
